export const DISCOMS = [
  {
    id: 'apspdcl',
    acronym: 'APSPDCL',
    fullName: 'Andhra Pradesh Southern Power Distribution Company Limited',
    hq: 'Tirupati',
    theme: 'southern',
    payUrl: 'https://payments.billdesk.com/MercOnline/SPDCLController',
    payLabel: 'Go to APSPDCL Official Site',
    redirectNote: 'Opens payments.billdesk.com in a new tab',
    helpline: '1912 | 180042155333',
    districts: [
      'Tirupati',
      'Chittoor',
      'Annamayya',
      'YSR Kadapa',
      'Anantapuramu',
      'Sri Sathya Sai',
      'Kurnool',
      'Nandyal',
      'SPSR Nellore',
    ],
  },
  {
    id: 'apcpdcl',
    acronym: 'APCPDCL',
    fullName: 'Andhra Pradesh Central Power Distribution Corporation Limited',
    hq: 'Vijayawada',
    theme: 'central',
    payUrl: 'https://www.apcpdcl.in/ConsumerDashboard/KnownBillPay',
    payLabel: 'Go to APCPDCL Official Site',
    redirectNote: 'Opens apcpdcl.in in a new tab',
    helpline: '1912 | 18004251912',
    districts: [
      'Krishna (NTR)',
      'Guntur',
      'Bapatla',
      'Palnadu',
      'Prakasam',
      'Markapuram',
    ],
  },
  {
    id: 'apepdcl',
    acronym: 'APEPDCL',
    fullName: 'Andhra Pradesh Eastern Power Distribution Company Limited',
    hq: 'Visakhapatnam',
    theme: 'eastern',
    payUrl: 'https://www.apeasternpower.com/payWithoutLogin',
    payLabel: 'Go to APEPDCL Official Site',
    redirectNote: 'Opens apeasternpower.com in a new tab',
    helpline: '1912 | 18004251912',
    districts: [
      'Srikakulam',
      'Vizianagaram',
      'Parvathipuram Manyam',
      'Visakhapatnam',
      'Anakapalli',
      'Alluri Sitharama Raju',
      'Kakinada',
      'East Godavari',
      'Konaseema',
      'Eluru',
      'West Godavari',
      'Polavaram',
    ],
  },
];
